// Auth
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const SET_REGISTER_ERROR = 'SET_REGISTER_ERROR';
export const RESET_REGISTER_ERROR = 'RESET_REGISTER_ERROR';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const RESET_LOGIN_ERROR = 'RESET_LOGIN_ERROR';

// Posts
export const ADD_POST = 'ADD_POST';
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const POST_ERROR = 'POST_ERROR';
export const SET_POSTS_LOADING = 'SET_POSTS_LOADING';
export const ADD_COMMENT = 'ADD_COMMENT';
export const GET_COMMENTS = 'GET_COMMENTS';
export const SET_COMMENTS_LOADING = 'SET_COMMENTS_LOADING';
export const GET_LATEST_POSTS = 'GET_LATEST_POSTS';
export const SET_LATEST_POSTS_LOADING = 'SET_LATEST_POSTS_LOADING';
export const GET_LATEST_COMMENTS = 'GET_LATEST_COMMENTS';
export const SET_LATEST_COMMENTS_LOADING = 'SET_LATEST_COMMENTS_LOADING';
